# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e7f1d3f2389a1b4cae7b7a22ac28ba1cf5678a2874f4861c9d5ef840b2c5ede9fb40ffbda6adc43f46c04230dd161d700a0031738dd17c7e74ccd26496d77ab

test:
  secret_key_base: 356a982eebe9efbd4fe4520ed4d62d37b623b18bb0920a28298c35bb2d59beb36d7864692c89367e4b6676c077bc4eb924719ab5d64687618d29804336daf79e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
